// Regenerates the time-zone coordinate table at `src/tz-coords.ts`.
// Run from the workspace root with `bun run vendor:tz`.
//
// Upstream is the IANA tz database's `zone.tab` (public domain), which
// lists every canonical zone name with the coordinates of its principal
// location in ISO 6709 form (`+4230+00131`, `-3749+14458`). We use the
// deprecated `zone.tab` rather than `zone1970.tab` on purpose: browsers
// report a zone name from the older, wider set (one row per country and
// zone, e.g. both `Europe/Oslo` and `Europe/Stockholm`), and the name
// `Intl.DateTimeFormat().resolvedOptions().timeZone` hands back has to
// hit the table directly. Browsers on ICU still report some names from
// the `backward` link file (`Asia/Calcutta`, `America/Buenos_Aires`,
// `Europe/Kiev`), so every link is folded in with its target's point.
//
// The consumer is a geocoder bias (see `geocode.ts`): a point the search
// ranks around so an ambiguous name resolves to the nearby one. A zone's
// principal city is a coarse but permission-free stand-in for "where the
// user is". Coordinates are rounded to two decimals (~1km), which is
// already past `zone.tab`'s own arc-minute precision.

const UPSTREAM_BASE = "https://data.iana.org/time-zones/tzdb/";

const outPath = new URL("../src/tz-coords.ts", import.meta.url);

async function fetchText(name: string): Promise<string> {
  const url = UPSTREAM_BASE + name;
  console.log(`fetching ${url}`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`upstream fetch failed: ${res.status} ${res.statusText}`);
  return res.text();
}

/** ISO 6709 `±DDMM[SS]±DDDMM[SS]` to decimal degrees. */
function parseCoords(s: string): [number, number] {
  const m = /^([+-])(\d{2})(\d{2})(\d{2})?([+-])(\d{3})(\d{2})(\d{2})?$/.exec(s);
  if (!m) throw new Error(`unparseable coordinates: ${s}`);
  const toDeg = (sign: string, d: string, min: string, sec: string | undefined) => {
    const v = Number(d) + Number(min) / 60 + (sec ? Number(sec) / 3600 : 0);
    return Math.round((sign === "-" ? -v : v) * 100) / 100;
  };
  return [toDeg(m[1]!, m[2]!, m[3]!, m[4]), toDeg(m[5]!, m[6]!, m[7]!, m[8])];
}

const version = (await fetchText("version")).trim();
const tab = await fetchText("zone.tab");
const backward = await fetchText("backward");

const rows: [string, number, number][] = [];
for (const line of tab.split("\n")) {
  if (!line || line.startsWith("#")) continue;
  const [, coords, zone] = line.split("\t");
  if (!coords || !zone) throw new Error(`malformed row: ${line}`);
  rows.push([zone, ...parseCoords(coords)]);
}

// `Link TARGET LINK-NAME` lines; targets may themselves be links, so
// resolve through the chain. Names that end nowhere in `zone.tab` (the
// `Etc/*` family, bare `GMT`, `UTC`) carry no geography and are skipped.
const links = new Map<string, string>();
for (const line of backward.split("\n")) {
  const m = /^Link\s+(\S+)\s+(\S+)/.exec(line);
  if (m) links.set(m[2]!, m[1]!);
}
const byZone = new Map(rows.map((r) => [r[0], r] as const));
let linked = 0;
for (const [name] of links) {
  if (byZone.has(name)) continue;
  let target: string | undefined = name;
  for (let hops = 0; target && !byZone.has(target) && hops < 8; hops++) target = links.get(target);
  const hit = target && byZone.get(target);
  if (!hit) continue;
  rows.push([name, hit[1], hit[2]]);
  linked++;
}
rows.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));

const body = rows.map(([zone, lat, lon]) => `  "${zone}": [${lat}, ${lon}],`).join("\n");
const out = `// GENERATED by scripts/vendor-tz.ts from IANA tzdb ${version} zone.tab; do not edit.
// Principal location of each canonical time zone, [lat, lon] in decimal
// degrees, rounded to two places. See the script for why and how.

export const TZ_COORDS: Readonly<Record<string, readonly [number, number]>> = {
${body}
};
`;

await Bun.write(outPath, out);
console.log(`wrote ${rows.length} zones (${linked} via backward links, tzdb ${version}) to ${outPath.pathname}`);
